# Generated by Django 5.1.2 on 2024-11-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_participante', to='torneo.participante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__nombre': 'Equipo'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_equipo', to='torneo.participante'),
        ),
    ]
