# Generated by Django 5.1.2 on 2024-11-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_tipocompetencia'),
        ('torneo', '0003_jugador_categoria_jugador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='competencia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='catalogo.tipocompetencia'),
            preserve_default=False,
        ),
    ]
