# Generated by Django 5.1.2 on 2024-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_jugador_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='coach',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=None),
        ),
    ]
