# Generated by Django 5.1.2 on 2024-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_alter_jugador_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VW_Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField(default=None)),
                ('sexo', models.CharField(max_length=10)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria_id', models.IntegerField()),
                ('Grado', models.CharField(max_length=100)),
                ('tipo_id', models.IntegerField()),
                ('Categoria', models.CharField(max_length=100)),
                ('competencia_id', models.IntegerField()),
                ('Competencia', models.CharField(max_length=100)),
                ('coach', models.IntegerField()),
                ('equipo', models.IntegerField()),
                ('Escuela', models.CharField(max_length=100)),
            ],
        ),
    ]
