# Generated by Django 5.1.2 on 2024-11-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_alter_vw_jugador_options_areastorneo_gruposareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposareas',
            name='torneo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_torneo', to='torneo.torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='nareas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='vw_jugador',
            table='vw_jugador',
        ),
    ]
