# Generated by Django 5.1.2 on 2024-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_vw_grupos_concentrado_kata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='coach',
            field=models.IntegerField(),
        ),
    ]
