# Generated by Django 5.1.2 on 2024-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0013_alter_jugador_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='VW_Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vw_horario',
                'managed': False,
            },
        ),
    ]
